### ISSUE TITLE
Should be able to return a Promise from the `processingFunction`

### ISSUE THREAD

**Issue by cbraynor** [FirebaseExtended/firebase-queue#25]
Instead of directly calling `resolve()` or `reject()` you should be able to return a Promise from the `processingFunction` - just like how mocha handles with/without a `done` callback - this would avoid the awkward `return somePromise.then(resolve, reject);`

**Comment by startswithaj** [comment]
n.b.

This is dangerous return somePromise.then(resolve, reject); because resolve and reject change behaviour depending on whats passed them them. So what somepromise returns can affect how the task is resolved.

somePromise.then(function(){resolve()}, function(){reject()})
